### ISSUE TITLE
BUILD FAILURE for mapr-spark-flightdelay

### ISSUE THREAD

**Issue by ruslan-gil** [mapr-demos/mapr-spark2-ebook#1]
[ERROR] Failed to execute goal on project mapr-spark-flightdelay: Could not resolve dependencies for project mapr:mapr-spark-flightdelay:jar:1.0: Failed to collect dependencies at graphframes:graphframes:jar:0.5.0-spark2.1-s_2.11: Failed to read artifact descriptor for graphframes:graphframes:jar:0.5.0-spark2.1-s_2.11: Could not transfer artifact graphframes:graphframes:pom:0.5.0-spark2.1-s_2.11 from/to spark-packages (https://dl.bintray.com/spark-packages/maven/): Access denied to: https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.5.0-spark2.1-s_2.11/graphframes-0.5.0-spark2.1-s_2.11.pom , ReasonPhrase:Forbidden.

**Comment by tdunning** [comment]
Try updating the dependency to version 0.8

Happy to accept a pull request if you get something working.

**Comment by tdunning** [comment]
If you are using an older Spark, then 0.6 or 0.7 might be better than 0.8

**Comment by ruslan-gil** [comment]
Unfortunately the same with 0.8 -
[ERROR] Failed to execute goal on project mapr-spark-flightdelay: Could not resolve dependencies for project mapr:mapr-spark-flightdelay:jar:1.0: Failed to collect dependencies at graphframes:graphframes:jar:0.8.0-spark2.4-s_2.11: Failed to read artifact descriptor for graphframes:graphframes:jar:0.8.0-spark2.4-s_2.11: Could not transfer artifact graphframes:graphframes:pom:0.8.0-spark2.4-s_2.11 from/to spark-packages (https://dl.bintray.com/spark-packages/maven/): Access denied to: https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.8.0-spark2.4-s_2.11/graphframes-0.8.0-spark2.4-s_2.11.pom , ReasonPhrase:Forbidden.

**Comment by tdunning** [comment]
Looking at this with morning after eyes, I realize that part of the problem
is not the graphframes version, but also the graphframes/spark version
combination. You have to adjust to meet all three requirements of spark
version you have, graphframes version that works with that spark, spark
version that databricks cares to support for graphframes.

**Comment by caroljmcdonald** [comment]
graphframes was suppose to replace graphx and become a supported part of Spark. This did not happen. I am not sure if graphframes works with later versions of Spark. I have not tested it lately

**Comment by tdunning** [comment]
Carol,

Thanks for the feedback. It looks like the 0.8 version is supported for
Spark 3.0.

**Comment by ruslan-gil** [comment]
Carol, Ted, Updated POM for mapr-spark-flightdelay. Changed version packages for Mapr 6.2. Changed repository source for spark packages - https://repos.spark-packages.org. Compilation was successful
